# ============================================================
# BREAST CANCER CLASSIFICATION - STREAMLIT APPLICATION
# BITS PILANI M.TECH AIML / DSE
# MACHINE LEARNING ASSIGNMENT - 2
# ============================================================

import os
import joblib
import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    confusion_matrix,
    classification_report
)


# ============================================================
# 1. PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Breast Cancer Classification",
    page_icon="🩺",
    layout="wide"
)


# ============================================================
# 2. APPLICATION TITLE
# ============================================================

st.title("🩺 Breast Cancer Classification")

st.markdown(
    """
    ### Machine Learning Assignment - 2

    This application evaluates multiple classification models
    using the Breast Cancer Wisconsin Diagnostic dataset.

    The application provides:
    - Test CSV upload
    - Model selection
    - Accuracy
    - AUC
    - Precision
    - Recall
    - F1 Score
    - MCC
    - Confusion Matrix
    - Classification Report
    - Prediction Results
    """
)


# ============================================================
# 3. DATASET INFORMATION
# ============================================================

st.sidebar.header("Dataset Information")

st.sidebar.write(
    """
    **Dataset:** Breast Cancer Wisconsin Diagnostic

    **Instances:** 569

    **Features:** 30

    **Problem:** Binary Classification

    **B:** Benign

    **M:** Malignant
    """
)


# ============================================================
# 4. MODEL FILE CONFIGURATION
# ============================================================

MODEL_FILES = {

    "Logistic Regression":
        "model/logistic_regression.pkl",

    "Decision Tree":
        "model/decision_tree.pkl",

    "kNN":
        "model/knn.pkl",

    "Naive Bayes":
        "model/naive_bayes.pkl",

    "Random Forest":
        "model/random_forest.pkl"
}


# ============================================================
# 5. EXPECTED FEATURE NAMES
# ============================================================

EXPECTED_FEATURES = [

    "radius_mean",
    "texture_mean",
    "perimeter_mean",
    "area_mean",
    "smoothness_mean",
    "compactness_mean",
    "concavity_mean",
    "concave points_mean",
    "symmetry_mean",
    "fractal_dimension_mean",

    "radius_se",
    "texture_se",
    "perimeter_se",
    "area_se",
    "smoothness_se",
    "compactness_se",
    "concavity_se",
    "concave points_se",
    "symmetry_se",
    "fractal_dimension_se",

    "radius_worst",
    "texture_worst",
    "perimeter_worst",
    "area_worst",
    "smoothness_worst",
    "compactness_worst",
    "concavity_worst",
    "concave points_worst",
    "symmetry_worst",
    "fractal_dimension_worst"
]


# ============================================================
# 6. MODEL SELECTION
# ============================================================

st.sidebar.header("Model Selection")

selected_model = st.sidebar.selectbox(
    "Select Classification Model:",
    list(MODEL_FILES.keys())
)

st.sidebar.write(
    f"**Selected Model:** {selected_model}"
)


# ============================================================
# 7. UPLOAD TEST DATA
# ============================================================

st.header("1️⃣ Upload Test Data")

st.write(
    """
    Upload the `test_data.csv` generated by the training program.

    The uploaded file must contain the 30 model features and the
    `diagnosis` target column.
    """
)

# Always initialize the variable before using it.
# This prevents NameError during Streamlit reruns.
test_data = None

uploaded_file = st.file_uploader(
    "Choose test_data.csv",
    type=["csv"],
    key="test_data_uploader"
)


# ============================================================
# 8. CHECK WHETHER FILE IS UPLOADED
# ============================================================

if uploaded_file is None:

    st.info(
        "Please upload `test_data.csv` to continue."
    )

    st.stop()


# ============================================================
# 9. READ THE UPLOADED CSV
# ============================================================

try:

    # Create test_data immediately after a file is available.
    test_data = pd.read_csv(uploaded_file)

except Exception as error:

    st.error(
        f"Unable to read the uploaded CSV file: {error}"
    )

    st.stop()


# ============================================================
# 10. VERIFY test_data
# ============================================================

if test_data is None:

    st.error(
        "Test data could not be loaded. Please upload a valid CSV file."
    )

    st.stop()


if test_data.empty:

    st.error(
        "The uploaded CSV is empty. Please upload a valid test_data.csv file."
    )

    st.stop()


# ============================================================
# 11. DISPLAY UPLOAD SUCCESS
# ============================================================

st.success(
    f"Test data uploaded successfully: "
    f"{test_data.shape[0]} rows × "
    f"{test_data.shape[1]} columns"
)


# ============================================================
# 12. DISPLAY TEST DATA PREVIEW
# ============================================================

with st.expander(
    "View Uploaded Test Data",
    expanded=False
):

    st.dataframe(
        test_data.head(10),
        use_container_width=True
    )


# ============================================================
# 13. CHECK TARGET COLUMN
# ============================================================

if "diagnosis" not in test_data.columns:

    st.error(
        """
        The uploaded CSV does not contain the required `diagnosis` column.

        Please upload the `test_data.csv` generated by the training program.
        """
    )

    st.stop()


# ============================================================
# 14. REMOVE UNNECESSARY COLUMNS IF PRESENT
# ============================================================

columns_to_remove = [
    column
    for column in ["id", "Unnamed: 32"]
    if column in test_data.columns
]

if columns_to_remove:

    test_data = test_data.drop(
        columns=columns_to_remove
    )


# ============================================================
# 15. SEPARATE TARGET FROM FEATURES
# ============================================================

y_test = test_data["diagnosis"].copy()

X_test = test_data.drop(
    columns=["diagnosis"]
)


# ============================================================
# 16. CONVERT TARGET VALUES
# ============================================================

# Original dataset:
# B = Benign
# M = Malignant

if y_test.dtype == "object":

    y_test = y_test.replace(
        {
            "B": 0,
            "M": 1,
            "Benign": 0,
            "Malignant": 1
        }
    )


# Convert target to numeric.
# Invalid values become NaN and are handled below.
y_test = pd.to_numeric(
    y_test,
    errors="coerce"
)


# ============================================================
# 17. VALIDATE TARGET VALUES
# ============================================================

if y_test.isnull().any():

    st.error(
        """
        Invalid or missing values were found in the `diagnosis` column.

        Expected values are:

        B = Benign
        M = Malignant

        or

        0 = Benign
        1 = Malignant
        """
    )

    st.stop()


valid_target_values = set(
    y_test.unique()
)

if not valid_target_values.issubset({0, 1}):

    st.error(
        "The diagnosis column must contain only 0/1 or B/M values."
    )

    st.stop()


# ============================================================
# 18. EXPECTED FEATURES
# ============================================================

# These names and order must match the features used while training.
EXPECTED_FEATURES = [

    "radius_mean",
    "texture_mean",
    "perimeter_mean",
    "area_mean",
    "smoothness_mean",
    "compactness_mean",
    "concavity_mean",
    "concave points_mean",
    "symmetry_mean",
    "fractal_dimension_mean",

    "radius_se",
    "texture_se",
    "perimeter_se",
    "area_se",
    "smoothness_se",
    "compactness_se",
    "concavity_se",
    "concave points_se",
    "symmetry_se",
    "fractal_dimension_se",

    "radius_worst",
    "texture_worst",
    "perimeter_worst",
    "area_worst",
    "smoothness_worst",
    "compactness_worst",
    "concavity_worst",
    "concave points_worst",
    "symmetry_worst",
    "fractal_dimension_worst"
]


# ============================================================
# 19. CHECK REQUIRED FEATURES
# ============================================================

missing_features = [
    feature
    for feature in EXPECTED_FEATURES
    if feature not in X_test.columns
]

if missing_features:

    st.error(
        "The following required features are missing from the uploaded CSV:"
    )

    st.write(missing_features)

    st.stop()


# ============================================================
# 20. SELECT FEATURES IN TRAINING ORDER
# ============================================================

X_test = X_test[
    EXPECTED_FEATURES
]


# ============================================================
# 21. CHECK FOR MISSING VALUES
# ============================================================

missing_value_count = int(
    X_test.isnull().sum().sum()
)

if missing_value_count > 0:

    st.error(
        f"""
        The uploaded test data contains {missing_value_count} missing values.

        Please use the `test_data.csv` generated by the training program.
        """
    )

    st.stop()


# ============================================================
# 22. DISPLAY TEST DATA SUMMARY
# ============================================================

st.header("2️⃣ Test Data Summary")

col1, col2, col3, col4 = st.columns(4)

with col1:

    st.metric(
        "Test Records",
        X_test.shape[0]
    )

with col2:

    st.metric(
        "Features",
        X_test.shape[1]
    )

with col3:

    st.metric(
        "Benign",
        int((y_test == 0).sum())
    )

with col4:

    st.metric(
        "Malignant",
        int((y_test == 1).sum())
    )


# ============================================================
# 21. MODEL PATH
# ============================================================

model_path = MODEL_FILES[
    selected_model
]


# ============================================================
# 22. CHECK MODEL FILE
# ============================================================

if not os.path.exists(
    model_path
):

    st.error(
        f"""
        Model file not found:

        `{model_path}`

        Please run the model-training program first
        and make sure the model folder contains all
        required `.pkl` files.
        """
    )

    st.stop()


# ============================================================
# 23. LOAD MODEL
# ============================================================

try:

    model = joblib.load(
        model_path
    )

except Exception as error:

    st.error(
        f"Unable to load model: {error}"
    )

    st.stop()


# ============================================================
# 24. MAKE PREDICTIONS
# ============================================================

try:

    y_pred = model.predict(
        X_test
    )

except Exception as error:

    st.error(
        """
        Prediction failed.

        This usually happens when the model was trained
        using scaled data but the saved model does not
        contain the scaler.

        Original error:
        """
    )

    st.exception(
        error
    )

    st.stop()


# ============================================================
# 25. GET PROBABILITY / DECISION SCORES
# ============================================================

try:

    if hasattr(
        model,
        "predict_proba"
    ):

        y_prob = model.predict_proba(
            X_test
        )[:, 1]

    elif hasattr(
        model,
        "decision_function"
    ):

        y_prob = model.decision_function(
            X_test
        )

    else:

        st.error(
            """
            The selected model does not provide
            probability or decision scores required
            for AUC calculation.
            """
        )

        st.stop()

except Exception as error:

    st.error(
        f"Unable to calculate probability scores: {error}"
    )

    st.stop()


# ============================================================
# 26. CALCULATE EVALUATION METRICS
# ============================================================

accuracy = accuracy_score(
    y_test,
    y_pred
)


auc_score = roc_auc_score(
    y_test,
    y_prob
)


precision = precision_score(
    y_test,
    y_pred,
    zero_division=0
)


recall = recall_score(
    y_test,
    y_pred,
    zero_division=0
)


f1 = f1_score(
    y_test,
    y_pred,
    zero_division=0
)


mcc = matthews_corrcoef(
    y_test,
    y_pred
)


# ============================================================
# 27. DISPLAY EVALUATION METRICS
# ============================================================

st.header(
    "3️⃣ Model Evaluation Metrics"
)

st.subheader(
    f"Selected Model: {selected_model}"
)


metric1, metric2, metric3 = st.columns(3)


with metric1:

    st.metric(
        "Accuracy",
        f"{accuracy:.4f}"
    )

    st.metric(
        "Precision",
        f"{precision:.4f}"
    )


with metric2:

    st.metric(
        "AUC",
        f"{auc_score:.4f}"
    )

    st.metric(
        "Recall",
        f"{recall:.4f}"
    )


with metric3:

    st.metric(
        "F1 Score",
        f"{f1:.4f}"
    )

    st.metric(
        "MCC",
        f"{mcc:.4f}"
    )


# ============================================================
# 28. CONFUSION MATRIX
# ============================================================

st.header(
    "4️⃣ Confusion Matrix"
)


cm = confusion_matrix(
    y_test,
    y_pred
)


cm_df = pd.DataFrame(
    cm,
    index=[
        "Actual Benign",
        "Actual Malignant"
    ],
    columns=[
        "Predicted Benign",
        "Predicted Malignant"
    ]
)


col1, col2 = st.columns(2)


with col1:

    st.subheader(
        "Confusion Matrix Table"
    )

    st.dataframe(
        cm_df,
        use_container_width=True
    )


with col2:

    st.subheader(
        "Confusion Matrix Visualization"
    )

    fig, ax = plt.subplots(
        figsize=(5, 4)
    )

    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        cmap="Blues",
        xticklabels=[
            "Benign",
            "Malignant"
        ],
        yticklabels=[
            "Benign",
            "Malignant"
        ],
        ax=ax
    )

    ax.set_xlabel(
        "Predicted Class"
    )

    ax.set_ylabel(
        "Actual Class"
    )

    ax.set_title(
        f"{selected_model} - Confusion Matrix"
    )

    st.pyplot(
        fig
    )

    plt.close(fig)


# ============================================================
# 29. CLASSIFICATION REPORT
# ============================================================

st.header(
    "5️⃣ Classification Report"
)


classification_report_dict = classification_report(
    y_test,
    y_pred,
    target_names=[
        "Benign",
        "Malignant"
    ],
    output_dict=True,
    zero_division=0
)


classification_report_df = pd.DataFrame(
    classification_report_dict
).transpose()


st.dataframe(
    classification_report_df.round(4),
    use_container_width=True
)


# ============================================================
# 30. PREDICTION RESULTS
# ============================================================

st.header(
    "6️⃣ Prediction Results"
)


prediction_results = X_test.copy()


prediction_results[
    "Actual Diagnosis"
] = np.where(
    y_test == 1,
    "Malignant",
    "Benign"
)


prediction_results[
    "Predicted Diagnosis"
] = np.where(
    y_pred == 1,
    "Malignant",
    "Benign"
)


prediction_results[
    "Prediction Probability"
] = y_prob


prediction_results[
    "Correct Prediction"
] = (
    y_test.values == y_pred
)


st.dataframe(
    prediction_results,
    use_container_width=True
)


# ============================================================
# 31. PREDICTION SUMMARY
# ============================================================

correct_predictions = int(
    (
        prediction_results[
            "Correct Prediction"
        ]
    ).sum()
)


incorrect_predictions = (
    len(prediction_results)
    - correct_predictions
)


st.subheader(
    "Prediction Summary"
)


col1, col2, col3 = st.columns(3)


with col1:

    st.metric(
        "Total Predictions",
        len(prediction_results)
    )


with col2:

    st.metric(
        "Correct Predictions",
        correct_predictions
    )


with col3:

    st.metric(
        "Incorrect Predictions",
        incorrect_predictions
    )


# ============================================================
# 32. DOWNLOAD PREDICTION RESULTS
# ============================================================

st.header(
    "7️⃣ Download Results"
)


csv_output = prediction_results.to_csv(
    index=False
)


st.download_button(
    label="⬇️ Download Prediction Results",
    data=csv_output,
    file_name="prediction_results.csv",
    mime="text/csv"
)


# ============================================================
# 33. MODEL COMPARISON
# ============================================================

st.header(
    "8️⃣ Model Comparison"
)


comparison_file = "model_comparison.csv"


if os.path.exists(
    comparison_file
):

    try:

        comparison_df = pd.read_csv(
            comparison_file
        )

        display_columns = [
            "ML Model Name",
            "Accuracy",
            "AUC",
            "Precision",
            "Recall",
            "F1 Score",
            "MCC"
        ]

        available_columns = [
            column
            for column in display_columns
            if column in comparison_df.columns
        ]

        comparison_display = comparison_df[
            available_columns
        ].copy()


        st.dataframe(
            comparison_display.round(4),
            use_container_width=True
        )


        # ----------------------------------------------------
        # Determine best model based on average metrics
        # ----------------------------------------------------

        required_metrics = [
            "Accuracy",
            "AUC",
            "Precision",
            "Recall",
            "F1 Score",
            "MCC"
        ]


        if all(
            metric in comparison_df.columns
            for metric in required_metrics
        ):

            comparison_df[
                "Average Score"
            ] = comparison_df[
                required_metrics
            ].mean(
                axis=1
            )


            best_model_row = comparison_df.loc[
                comparison_df[
                    "Average Score"
                ].idxmax()
            ]


            st.success(
                f"""
                Overall best model based on the average
                of the six evaluation metrics:

                **{best_model_row["ML Model Name"]}**

                Average Score:
                **{best_model_row["Average Score"]:.4f}**
                """
            )


    except Exception as error:

        st.warning(
            f"Unable to read model_comparison.csv: {error}"
        )


else:

    st.info(
        """
        `model_comparison.csv` was not found.

        Run the training program first to generate
        the model comparison file.
        """
    )


# ============================================================
# 34. APPLICATION INFORMATION
# ============================================================

st.markdown(
    "---"
)

st.subheader(
    "About This Application"
)

st.write(
    """
    This Streamlit application was developed as part of the
    BITS Pilani M.Tech AIML/DSE Machine Learning Assignment-2.

    The application demonstrates an end-to-end classification
    workflow using the Breast Cancer Wisconsin Diagnostic dataset.

    Models implemented:

    • Logistic Regression
    • Decision Tree
    • kNN
    • Gaussian Naive Bayes
    • Random Forest
    • SVC (additional model)

    Evaluation metrics:

    • Accuracy
    • AUC
    • Precision
    • Recall
    • F1 Score
    • Matthews Correlation Coefficient (MCC)
    """
)


# ============================================================
# 35. FOOTER
# ============================================================

st.markdown(
    "---"
)

st.caption(
    "BITS Pilani | M.Tech AIML/DSE | Machine Learning Assignment-2"
)